### ISSUE TITLE
moon add moonbitlang/x error: could not find the latest version of moonbitlang/x

### ISSUE THREAD

**Issue by npmstudy** [moonbitlang/x#12]
```
$ moon add moonbitlang/x
error: could not find the latest version of moonbitlang/x
```

**Comment by npmstudy** [comment]
moon version
moon 0.1.20240603 (c0289e3 2024-06-03)

**Comment by npmstudy** [comment]
moon upgrade
Checking network ...
  Use https://cli.moonbitlang.com
Warning: moon upgrade is highly experimental.
If you encounter any problems, please reinstall by visit https://www.moonbitlang.com/download
Will install to /Users/bytedance/.moon. Continue? yes
Downloading 100.0%
moon version:
Compiling moonbitlang/core ...
moon 0.1.20240603 (c0289e3 2024-06-03)

# not work

**Comment by npmstudy** [comment]
参考 https://github.com/moonbitlang/core/blob/main/CONTRIBUTING.md，也不行

**Comment by lijunchen** [comment]
Can you try

```
moon update
moon add moonbitlang/x
```

**Comment by npmstudy** [comment]
![image](https://github.com/moonbitlang/x/assets/26357769/27e33b44-d03c-4593-8535-5763ee8b6568)

**Comment by npmstudy** [comment]
failed: moonc build-package /Users/bytedance/workspace/github/koa-demo/lib/app.mbt /Users/bytedance/workspace/github/koa-demo/lib/hello.mbt -o /Users/bytedance/workspace/github/koa-demo/target/js/release/build/lib/lib.core -pkg username/hello/lib -std-path /Users/bytedance/.moon/lib/core/target/js/release/bundle -pkg-sources username/hello/lib:/Users/bytedance/workspace/github/koa-demo/lib
Fatal error: exception Sys_error("/Users/bytedance/.moon/lib/core/target/js/release/bundle: No such file or directory")
error: failed when building

构建不成功

**Comment by Yoorkin** [comment]
version 0.4.2 has been released on mooncakes.io
